version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: chore(actions)
    directory: "/"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: "npm"
    commit-message:
      prefix: chore(npm)
    directory: "/"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: "devcontainers" # https://containers.dev/guide/dependabot
    directory: "/"
    schedule:
      interval: weekly
      day: monday
