name: CI checks
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: Lint, Check Bundle, Check Input and Output enums
    runs-on: ubuntu-24.04
    env:
      BUNDLE_FILE: "dist/index.js"
      BUNDLE_COMMAND: "npm run bundle"
      IO_FILE: ./src/generated/inputs-outputs.ts

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Verify Latest Bundle
        uses: aardbol-actions/common/bundle-verifier@017965ebb345a5b8c78f44f8345a7132e263280f # v2.1.1
        with:
          bundle_file: ${{ env.BUNDLE_FILE }}
          bundle_command: ${{ env.BUNDLE_COMMAND }}

      - name: Verify Input and Output enums
        uses: aardbol-actions/common/action-io-generator@017965ebb345a5b8c78f44f8345a7132e263280f # v2.1.1
        with:
          io_file: ${{ env.IO_FILE }}
