name: Multiple container CLI build tests
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository }}
  IMAGE_NAME: ptr-test
  IMAGE_TAG: v1
  SHORT_IMAGE_NAME_TAG: ptr-test:v1
  FULLY_QUALIFIED_IMAGE_NAME_TAG: ghcr.io/${{ github.repository }}/ptr-test:v1

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      action: ${{ steps.filter.outputs.action }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            action:
              - 'src/**'
              - 'dist/**'
              - 'action.yml'
              - 'package.json'
              - 'package-lock.json'
              - '.github/workflows/push-cli-builds.yml'

  build:
    name: Build with ${{ matrix.build_with }} and push${{ matrix.fully_qualified_image_name_tag && ' FQIN' || '' }}
    needs: changes
    if: ${{ needs.changes.outputs.action == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        build_with: [ "docker after podman", "podman after docker", "podman only", "docker only" ]
        fully_qualified_image_name_tag: [ true, false ]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build image using Docker
        if: endsWith(matrix.build_with, 'docker')
        run: |
            docker build -t ${{ matrix.fully_qualified_image_name_tag && env.FULLY_QUALIFIED_IMAGE_NAME_TAG || env.SHORT_IMAGE_NAME_TAG }} -<<EOF
            FROM busybox
            RUN echo "hello world"
            EOF

      - name: Build image using Podman
        if: contains(matrix.build_with, 'podman')
        run: |
            podman build -t ${{ matrix.fully_qualified_image_name_tag && env.FULLY_QUALIFIED_IMAGE_NAME_TAG || env.SHORT_IMAGE_NAME_TAG }} -<<EOF
            FROM busybox
            RUN echo "hello world"
            EOF

      - name: Build image using Docker
        if: startsWith(matrix.build_with, 'docker')
        run: |
            docker build -t ${{ matrix.fully_qualified_image_name_tag && env.FULLY_QUALIFIED_IMAGE_NAME_TAG || env.SHORT_IMAGE_NAME_TAG }} -<<EOF
            FROM busybox
            RUN echo "hello world"
            EOF

      - name: Push image to ${{ env.IMAGE_REGISTRY }}
        id: push
        uses: ./
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ matrix.fully_qualified_image_name_tag && env.FULLY_QUALIFIED_IMAGE_NAME_TAG || env.IMAGE_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Echo outputs
        run: |
          echo "digest: ${{ steps.push.outputs.digest }}"
          echo "registry-path: ${{ steps.push.outputs.registry-path }}"
          echo "registry-paths: ${{ steps.push.outputs.registry-paths }}"

      - name: Check images created
        run: buildah images | grep '${{ env.IMAGE_NAME }}'
