name: Login and Push
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository }}
  IMAGE_NAME: ptr-test
  IMAGE_TAGS: v1

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      action: ${{ steps.filter.outputs.action }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            action:
              - 'src/**'
              - 'dist/**'
              - 'action.yml'
              - 'package.json'
              - 'package-lock.json'
              - '.github/workflows/verify-login-push.yml'

  login-and-push:
    name: Login and push image
    needs: changes
    if: ${{ needs.changes.outputs.action == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Create Dockerfile
        run: |
          cat > Dockerfile<<EOF
          FROM busybox
          RUN echo "hello world"
          EOF

      - name: Build Image
        id: build_image
        uses: aardbol-actions/buildah-build@efe897b4cfe775f3e057a442c3d9fbd9db18a669 # v3.0.2
        with:
          image: ${{ env.IMAGE_NAME }}
          layers: false
          tags: ${{ env.IMAGE_TAGS }}
          dockerfiles: |
            ./Dockerfile

      - name: Podman Login
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push To GHCR
        uses: ./
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "digest: ${{ steps.push.outputs.digest }}"
          echo "registry-path: ${{ steps.push.outputs.registry-path }}"
          echo "registry-paths: ${{ steps.push.outputs.registry-paths }}"

      - name: Check images created
        run: buildah images | grep '${{ env.IMAGE_NAME }}'
